# GitLab CI/CD pipeline 

variables:
  TARGETOS: "linux"
  TARGETARCH: "amd64"
  SKIP_TESTS: "false"
  SKIP_LINT: "false"

stages:
  - lint
  - test
  - build
  - docker
  - push

lint:
  stage: lint
  image: golang:1.21 # Use a Go image for linting
  script:
    - go install golang.org/x/lint/golint@latest
    - export PATH=$PATH:$(go env GOPATH)/bin
    - if [ "$SKIP_LINT" != "true" ]; then make lint; fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always

test:
  stage: test
  image: golang:1.21
  script:
    - if [ "$SKIP_TESTS" != "true" ]; then make test; fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push"'
      when: always

build:
  stage: build
  image: golang:1.21
  script:
    - |
      if [ "$TARGETOS" = "linux" ] && [ "$TARGETARCH" = "amd64" ]; then make linux;
      elif [ "$TARGETOS" = "linux" ] && [ "$TARGETARCH" = "arm64" ]; then make arm;
      elif [ "$TARGETOS" = "darwin" ] && [ "$TARGETARCH" = "amd64" ]; then make macos;
      elif [ "$TARGETOS" = "darwin" ] && [ "$TARGETARCH" = "arm64" ]; then make macos-arm;
      elif [ "$TARGETOS" = "windows" ] && [ "$TARGETARCH" = "amd64" ]; then make windows;
      elif [ "$TARGETOS" = "windows" ] && [ "$TARGETARCH" = "arm64" ]; then make windows-arm;
      fi
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always

.make_install: &make_install
  - apk add --no-cache make

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - *make_install
    - make image
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always

push:
  stage: push
  image: docker:latest
  services:
    - docker:dind
  script:
    - *make_install
    - make push
  rules:
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"'
      when: always
