apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: tbot-repo
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/GregoryKoshelenko/tbot
  branch: main
